### ISSUE TITLE
Merge Noto fonts into one

### ISSUE THREAD

**Issue by rinigus** [otsaloma/cartago-styles#2]
I have written some scripts that allow to merge Noto fonts into a single font (regular + CJK). That would simplify writing of the styles since only one font needs to be mentioned. The scripts are available at https://github.com/rinigus/mapbox-gl-fonts . At present, they populate SQLite database. However, we can rewrite them for dumping glyphs into pbf files, as it is done usually. For me, SQLite was better due to simplicity of its upload/download and use.

**Comment by otsaloma** [comment]
OK by me, I guess. If I have understood correctly, the fonts are split so that western users can get by with smaller fonts, but for global use, there's no benefit, just a slight annoyance as multiple fonts are needed specified. So, if you or someone wants to do the work and make a PR, I expect I'll accept it.

**Comment by rinigus** [comment]
Sure, I can make the PR. Give me couple of days and it will be fine. 

As for splitting, Noto fonts have to be split due to the format limitations, as far as I understood.
